export const BlogData = [
  {
    id: 0,
    imgUrl: `/img/image 1.png`,
    title: `Navigating the Digital Age: How to Foster Healthy Screen Time Habits`,
    description: `Delve into the impactful world of positive reinforcement in parenting, where the strength of connections with teenagers is forged. Join us as we uncover stories... `,
    day: "24 Dec",
    minsRead: "8 min read",
  },
  {
    id: 1,
    imgUrl: `/img/image 2.png`,
    title: `The Power of Positive Reinforcement: Building Stronger Connections with Your Teen`,
    description: `Dive into the digital realm with insights and real-life experiences from parents on navigating screen time for children and teens.  Learn how families thrive in the digital world`,
    day: "9 October",
    minsRead: "10 min read",
  },
  {
    id: 2,
    imgUrl: `/img/image 3.png`,
    title: `Parenting Through Challenges: Coping Strategies for Tough Times`,
    description: `Explore common challenges, personal stories, and practical tips for navigating tough times. Learn how open communication helps in fostering stronger parent-teen connections.`,
    day: "17 January",
    minsRead: "5 min read",
  },
  {
    id: 3,
    imgUrl: `/img/image 4.png`,
    title: `Parenting Styles: Embracing Differences for a Unified Family`,
    description: `Explore common challenges, personal stories, and practical tips for navigating tough times. Learn how open communication helps in fostering stronger parent-teen connections.`,
    day: "8 April",
    minsRead: "5 min read",
  },
  {
    id: 4,
    imgUrl: `/img/image 5.png`,
    title: `The Art of Effective Communication: Bridging the Generation Gap`,
    description: `Explore common challenges, personal stories, and practical tips for navigating tough times. Learn how open communication helps in fostering stronger parent-teen connections.`,
    day: "2 February",
    minsRead: "8 min read",
  },
  {
    id: 5,
    imgUrl: `/img/image 6.png`,
    title: `Nurturing Confident Teens: Building Strong Foundations`,
    description: `Explore common challenges, personal stories, and practical tips for navigating tough times. Learn how open communication helps in fostering stronger parent-teen connections.`,
    day: "3 September",
    minsRead: "9 min read",
  },
];
